<a href="https://colab.research.google.com/github/GODHYEONJU/MS-AI-School-/blob/main/4_17_Numpy_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
#np는 list랑 비슷한 배열 형태, list와 다르게 하나의 요소들의 데이터 타입이 모두 동일!
print(arr)
print(type(arr)) #<class 'numpy.ndarray'> ndarray : n차원의 배열의 객체

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
ZeroCoke = np.zeros((3,3))
print(ZeroCoke)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
OneCoke = np.ones((1,2)) #(행, 열)
print(OneCoke)

[[1. 1.]]


In [12]:
np.empty((5,5))

array([[ 2.02005577e-316,  0.00000000e+000,  0.00000000e+000,
        -1.00000000e+000,  1.00000000e+000],
       [-2.00000000e+000,  2.00000000e+000, -1.00000000e+000,
         1.00000000e+000,  0.00000000e+000],
       [ 2.00000000e+000,  1.00000000e+000,  1.00000000e+000,
         2.00000000e+000,  0.00000000e+000],
       [ 1.00000000e+000, -1.00000000e+000,  2.00000000e+000,
        -2.00000000e+000,  1.00000000e+000],
       [-1.00000000e+000,  0.00000000e+000, -2.00000000e+000,
        -1.00000000e+000,  1.02765654e-321]])

In [13]:
print(np.arange(1,10,3)) #숫자의 끝나는 값은 항상 끝값 전까지 포함함
#(시작값, 끝값, 증가값)

[1 4 7]


In [15]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
 arr1 = np.array(((([1,2,3],[4,5,6],[7,8,9],[10,11,12]))))
 print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
arr2=arr[:2,1:3] #[시작행:마지막행, 시작열:마지막열]
print(arr2)

[[2 3]
 [5 6]]


In [28]:
redwine=np.loadtxt(fname='winequality-red.csv',
                   delimiter = ';',
                   skiprows=1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [35]:
print(redwine.sum())
print(redwine.sum(axis=0)) #axis=0, 가로축/행
print(redwine.sum(axis=1)) #axis=1, 세로축/열열
print(redwine.mean(axis=0))

152084.78194
[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 74.5438  123.0548   99.699   ... 100.48174 105.21547  92.49249]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [32]:
print(redwine[:,0]) #영번축

[7.4 7.8 7.8 ... 6.3 5.9 6. ]


In [33]:
print(redwine[:,0].mean()) #0번 행의 평균값

8.31963727329581


In [31]:
print(redwine.max(axis=0))
print(redwine.min(axis=0))

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]
[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
